/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsiannisameriana.soal;

import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import skripsiannisameriana.connect.Connect;

/**
 *
 * @author USER
 */
public class SoalView extends javax.swing.JInternalFrame {
    SoalImplements soalimpl = new SoalImplements();
    SoalTabelModel soaltabmod = new SoalTabelModel();
    int id;
    /**
     * Creates new form SoalView
     */
    public SoalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupKunciJawaban = new javax.swing.ButtonGroup();
        panelButton = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        panelIsi = new javax.swing.JPanel();
        txtKodeFakultas = new javax.swing.JTextField();
        txtNamaFakultas = new javax.swing.JTextField();
        btnCariProdi = new javax.swing.JButton();
        txtNamaProdi = new javax.swing.JTextField();
        txtKodeProdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSoal = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKunciA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNilaiA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtKunciB = new javax.swing.JTextField();
        txtKunciC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNilaiC = new javax.swing.JTextField();
        txtKunciD = new javax.swing.JTextField();
        txtNilaiD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNilaiB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNilaiKepentingan = new javax.swing.JTextField();
        panelData = new javax.swing.JPanel();
        ComboBoxCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSoal = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelButton.setForeground(new java.awt.Color(255, 255, 255));
        panelButton.setOpaque(false);
        panelButton.setLayout(new java.awt.GridLayout(1, 0));

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambah.setText("Baru");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelButton.add(btnTambah);

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        panelButton.add(btnUbah);

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelButton.add(btnHapus);

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelButton.add(btnBatal);

        btnTutup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        panelButton.add(btnTutup);

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        panelButton.add(btnCetak);

        panelIsi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Soal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        panelIsi.setOpaque(false);

        btnCariProdi.setText("Cari Prodi");
        btnCariProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Soal / Pertanyaan        :");

        txtAreaSoal.setColumns(20);
        txtAreaSoal.setRows(5);
        jScrollPane2.setViewportView(txtAreaSoal);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kunci Jawaban             :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fakultas                         :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nilai Kunci   :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nilai Kunci   :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nilai Kunci   :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Nilai Kunci   :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nilai Kepentingan        :");

        javax.swing.GroupLayout panelIsiLayout = new javax.swing.GroupLayout(panelIsi);
        panelIsi.setLayout(panelIsiLayout);
        panelIsiLayout.setHorizontalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsiLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelIsiLayout.createSequentialGroup()
                                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKunciC, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(txtKunciB)
                                    .addComponent(txtKunciA)
                                    .addComponent(txtKunciD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNilaiC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtNilaiD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNilaiB)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIsiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIsiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtNilaiKepentingan))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIsiLayout.createSequentialGroup()
                    .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelIsiLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKodeFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelIsiLayout.createSequentialGroup()
                            .addComponent(btnCariProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKodeProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNamaProdi, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addComponent(txtNamaFakultas))))
        );
        panelIsiLayout.setVerticalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsiLayout.createSequentialGroup()
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsiLayout.createSequentialGroup()
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtKunciA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKunciB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKunciC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKunciD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIsiLayout.createSequentialGroup()
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNilaiB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNilaiC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNilaiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNilaiKepentingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsiLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKodeFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNamaFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCariProdi)
                    .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKodeProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNamaProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panelData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Berdasarkan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelData.setForeground(new java.awt.Color(255, 255, 255));
        panelData.setOpaque(false);

        ComboBoxCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBoxCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Soal", "Soal", "Program Studi" }));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Soal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setOpaque(false);

        tabelSoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSoal.setOpaque(false);
        jScrollPane1.setViewportView(tabelSoal);

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ComboBoxCari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        buttonTambah();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        buttonUbah();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteSoal();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        refresh();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        buttonTutup();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        searchPeremeter();
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnCariProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdiActionPerformed
        btnCariProdi();
    }//GEN-LAST:event_btnCariProdiActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        refresh();
        setTableModel();
        tableSoalAction();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            String sqlParameter = null;
            String searchParameter;
            if(txtKodeProdi.getText().isEmpty()){
            String path1 = "src/laporan/Soal.jasper";
            JasperPrint print = JasperFillManager.fillReport(path1, null, Connect.getConnection());

            JasperViewer.viewReport(print, false);
            } else {//if(ComboBoxCari.getSelectedIndex() == 2) {
//                sqlParameter = "nama_prodi";
                int row = tabelSoal.getRowCount();
                
                HashMap parameter = new HashMap();
                //JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream("/laporan/SoalProdi.jasper"), null, Connect.getConnection());
                String path = "src/laporan/SoalProdi.jasper";
                //int id = txtKodeFakultas.getText();
                parameter.put("nama_prodi", txtNamaProdi.getText());
                //parameter.clear();

                //JasperPrint print = JasperFillManager.fillReport(path, parameter, Connect.getConnection());
                JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream(path), parameter, Connect.getConnection());

                JasperViewer.viewReport(print, false);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada " + ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCari;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariProdi;
    private javax.swing.JButton btnCetak;
    private javax.swing.ButtonGroup btnGrupKunciJawaban;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelIsi;
    private javax.swing.JTable tabelSoal;
    private javax.swing.JTextArea txtAreaSoal;
    private javax.swing.JTextField txtCari;
    public static javax.swing.JTextField txtKodeFakultas;
    public static javax.swing.JTextField txtKodeProdi;
    public static javax.swing.JTextField txtKunciA;
    public static javax.swing.JTextField txtKunciB;
    public static javax.swing.JTextField txtKunciC;
    public static javax.swing.JTextField txtKunciD;
    public static javax.swing.JTextField txtNamaFakultas;
    public static javax.swing.JTextField txtNamaProdi;
    public static javax.swing.JTextField txtNilaiA;
    public static javax.swing.JTextField txtNilaiB;
    public static javax.swing.JTextField txtNilaiC;
    public static javax.swing.JTextField txtNilaiD;
    public static javax.swing.JTextField txtNilaiKepentingan;
    // End of variables declaration//GEN-END:variables

    public void setTableModel() {
        try {
            tabelSoal.setModel(soaltabmod);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }

    public void loadDatabase() {
        try {
            List<Soal> list = soalimpl.getSoal();
            soaltabmod.setData(list);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }

    public void refresh() {
        try {
            loadDatabase();
                   
            btnCariProdi.setEnabled(true);
            txtKodeFakultas.setEnabled(false);
            txtNamaFakultas.setEnabled(false);
            txtKodeProdi.setEnabled(false);
            txtNamaProdi.setEnabled(false);

            txtKodeProdi.setText("");
            txtKodeFakultas.setText("");
            txtNamaFakultas.setText("");
            txtNamaProdi.setText("");
            txtAreaSoal.setText("");
            txtKunciA.setText("");
            txtNilaiA.setText("");
            txtKunciB.setText("");
            txtNilaiB.setText("");
            txtKunciC.setText("");
            txtNilaiC.setText("");
            txtKunciD.setText("");
            txtNilaiD.setText("");

            btnBatal.setEnabled(true);
            btnBatal.setText("Bersihkan");
            btnBatal.setToolTipText("Bersihkan");

            btnTambah.setEnabled(true);
            btnTambah.setText("Baru");
            btnTambah.setToolTipText("Baru");
//
            btnTutup.setEnabled(true);

            txtCari.setEnabled(true);
            ComboBoxCari.setEnabled(true);
            txtCari.setText("");
            ComboBoxCari.setSelectedIndex(0);

            //btnUbah.setEnabled(false);
            //btnHapus.setEnabled(false);

            tabelSoal.setEnabled(true);
            btnTambah.requestFocus();
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }

    public void buttonTambah() {
        try {
            switch (btnTambah.getToolTipText()) {
                case "Baru":
                    disableAndEnableForInsert();
                    break;
                case "Simpan":
                    if (txtAreaSoal.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "Isi'i bujur2 soalnya nang");
                        txtAreaSoal.requestFocus();
                    } else if (txtKunciA.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciA.requestFocus();
                    } else if (txtNilaiA.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiA.requestFocus();
                    } else if (txtKunciB.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciB.requestFocus();
                    } else if (txtNilaiB.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiB.requestFocus();
                    } else if (txtKunciC.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciC.requestFocus();
                    } else if (txtNilaiC.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiC.requestFocus();
                    } else if (txtKunciD.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciD.requestFocus();
                    } else if (txtNilaiD.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiD.requestFocus();
                    } else if (txtNamaFakultas.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Fakultas dan Program Studi!");
                        btnCariProdi.doClick();
                    } else {
                        insertSoal();
                    }
                    break;
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }

    public void buttonUbah() {
        try {
            switch (btnUbah.getToolTipText()) {
                case "Ubah":
                    disableAndEnableForUpdate();
                    break;
                case "Simpan":
                    if (txtAreaSoal.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "Isi'i bujur2 soalnya nang");
                        txtAreaSoal.requestFocus();
                    } else if (txtKunciA.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciA.requestFocus();
                    } else if (txtNilaiA.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiA.requestFocus();
                    } else if (txtKunciB.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciB.requestFocus();
                    } else if (txtNilaiB.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiB.requestFocus();
                    } else if (txtKunciC.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciC.requestFocus();
                    } else if (txtNilaiC.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiC.requestFocus();
                    } else if (txtKunciD.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Kunci dulu say!");
                        txtKunciD.requestFocus();
                    } else if (txtNilaiD.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Nilai dulu say!");
                        txtNilaiD.requestFocus();
                    } else if (txtNamaFakultas.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Lengkapi Data Fakultas dan Program Studi!");
                        btnCariProdi.doClick();
                    } else {
                        updateSoal();
                    }
                    break;
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan 232!");
        }
    }

    public void buttonTutup() {
        try {
            //Home2.setEnableDisableMenu(true);
            dispose();
            //Home2.isMenuItemKelasActive = false;
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan 5!");
        }
    }

    public void insertSoal() {
        try {
            Soal soal = new Soal();
            
            soal.setSoal(txtAreaSoal.getText());
            soal.setA(txtKunciA.getText());
            soal.setNilaiA(Integer.parseInt(txtNilaiA.getText()));
            soal.setB(txtKunciB.getText());
            soal.setNilaiB(Integer.parseInt(txtNilaiB.getText()));
            soal.setC(txtKunciC.getText());
            soal.setNilaiC(Integer.parseInt(txtNilaiC.getText()));
            soal.setD(txtKunciD.getText());
            soal.setNilaiD(Integer.parseInt(txtNilaiD.getText()));
            soal.setKepentingan(Integer.parseInt(txtNilaiKepentingan.getText()));
            soal.setIdFakultas(Integer.parseInt(txtKodeFakultas.getText()));
            soal.setNamaFakultas(txtNamaFakultas.getText());
            soal.setIdProdi(Integer.parseInt(txtKodeProdi.getText()));
            soal.setNamaProdi(txtNamaProdi.getText());
            
            soalimpl.insertSoal(soal);
            JOptionPane.showMessageDialog(null, "Program Studi " + txtNamaProdi.getText() + " Berhasil Di Simpan!");
            refresh();
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan 555!");
        }
    }

    public void updateSoal() {
        try {
            Soal soal = new Soal();
            
            soal.setSoal(txtAreaSoal.getText());
            soal.setA(txtKunciA.getText());
            soal.setNilaiA(Integer.parseInt(txtNilaiA.getText()));
            soal.setB(txtKunciB.getText());
            soal.setNilaiB(Integer.parseInt(txtNilaiB.getText()));
            soal.setC(txtKunciC.getText());
            soal.setNilaiC(Integer.parseInt(txtNilaiC.getText()));
            soal.setD(txtKunciD.getText());
            soal.setNilaiD(Integer.parseInt(txtNilaiD.getText()));
            soal.setKepentingan(Integer.parseInt(txtNilaiKepentingan.getText()));
            soal.setIdFakultas(Integer.parseInt(txtKodeFakultas.getText()));
            soal.setNamaFakultas(txtNamaFakultas.getText());
            soal.setIdProdi(Integer.parseInt(txtKodeProdi.getText()));
            soal.setNamaProdi(txtNamaProdi.getText());
            soal.setIdSoal(id);

            soalimpl.updateSoal(soal);
            JOptionPane.showMessageDialog(null, "Program Studi " + txtNamaProdi.getText() + " Berhasil Di Ubah!");
            refresh();

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan 999!");
        }
    }

    public void deleteSoal() {
        try {
            int row = tabelSoal.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan seleksi data yang ingin dihapus!");
            } else {
                int confirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Mau Menghapus Soal "
                        + soaltabmod.get(row).getSoal()+ "? \n", "Konfirmasi",
                        JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);

                //Periksa Jawaban yang dipilih
                if (confirm == JOptionPane.YES_OPTION) {
                    int idSoal = soaltabmod.get(row).getIdProdi();

                    soalimpl.deleteSoal(idSoal);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus Semua!");
                    refresh();
                } else if (confirm == JOptionPane.NO_OPTION) {
                    refresh();
                }
            }
        } catch (IndexOutOfBoundsException error) {
            System.out.println("Terjadi Kesalahan!");
        } catch (Exception error) {
            System.out.println("Terjadi Kesalahan!");
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }

    public void disableAndEnableForInsert() {
        try {
            txtKodeProdi.setEnabled(false);
            txtNamaProdi.setEnabled(false);
            txtKodeFakultas.setEnabled(false);
            txtNamaFakultas.setEnabled(false);
            
            btnCariProdi.setEnabled(true);
            
            txtKodeProdi.setText("");
            txtKodeFakultas.setText("");
            txtNamaFakultas.setText("");
            txtNamaProdi.setText("");
            txtAreaSoal.setText("");
            txtKunciA.setText("");
            txtNilaiA.setText("");
            txtKunciB.setText("");
            txtNilaiB.setText("");
            txtKunciC.setText("");
            txtNilaiC.setText("");
            txtKunciD.setText("");
            txtNilaiD.setText("");
            txtNilaiKepentingan.setText("");

            btnBatal.setEnabled(true);
            btnBatal.setText("Batal");
            btnBatal.setToolTipText("Batal");

            btnTambah.setEnabled(true);
            btnTambah.setText("Simpan");
            btnTambah.setToolTipText("Simpan");

            txtCari.setEnabled(false);
            ComboBoxCari.setEnabled(false);
            txtCari.setText("");
            ComboBoxCari.setSelectedIndex(0);

            tabelSoal.setEnabled(false);
            txtKodeProdi.requestFocus();

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }

    public void disableAndEnableForUpdate() {
        try {

            int row = tabelSoal.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan seleksi data yang ingin diubah!");
            } else {
                txtKodeProdi.setEnabled(false);
                txtNamaProdi.setEnabled(false);
                txtKodeFakultas.setEnabled(false);
                txtNamaFakultas.setEnabled(false);
                
                btnCariProdi.setEnabled(true);

                btnBatal.setEnabled(true);
                btnBatal.setText("Batal");
                btnBatal.setToolTipText("Batal");

                btnUbah.setEnabled(true);
                btnUbah.setText("Simpan");
                btnUbah.setToolTipText("Simpan");

                txtCari.setEnabled(false);
                ComboBoxCari.setEnabled(false);
                txtCari.setText("");
                ComboBoxCari.setSelectedIndex(0);

                tabelSoal.setEnabled(false);
                txtNamaProdi.requestFocus();
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }

    public void tableSoalAction() {
        tabelSoal.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tabelSoal.getSelectedRow();
                //CEK APAKAH BARIS BENAR2 TERSELEKSI
                if (row != -1) {
                    Soal soal = soaltabmod.get(row);
                    
                    txtAreaSoal.setText(soal.getSoal());
                    txtKunciA.setText(soal.getA());
                    txtNilaiA.setText(Integer.toString(soal.getNilaiA()));
                    txtKunciB.setText(soal.getB());
                    txtNilaiB.setText(Integer.toString(soal.getNilaiB()));
                    txtKunciC.setText(soal.getC());
                    txtNilaiC.setText(Integer.toString(soal.getNilaiC()));
                    txtKunciD.setText(soal.getD());
                    txtNilaiD.setText(Integer.toString(soal.getNilaiD()));
                    txtKodeProdi.setText(Integer.toString(soal.getIdProdi()));
                    txtNamaProdi.setText(soal.getNamaProdi());
                    txtKodeFakultas.setText(Integer.toString(soal.getIdFakultas()));
                    txtNamaFakultas.setText(soal.getNamaFakultas());
                    id = soal.getIdSoal();

                    btnUbah.setEnabled(true);
                    btnUbah.setText("Ubah");
                    btnUbah.setToolTipText("Ubah");
                    btnHapus.setEnabled(true);
                    btnUbah.requestFocus();
                }
            }
        });
    }

    public void searchPeremeter() {
        try {
            String sqlParameter = null;
            String searchParameter;
            if (ComboBoxCari.getSelectedIndex() == 0) {
                sqlParameter = "id_soal";
            } else if (ComboBoxCari.getSelectedIndex() == 1) {
                sqlParameter = "soal";
            } else if (ComboBoxCari.getSelectedIndex() == 2) {
                sqlParameter = "tb_prodi.nama_prodi";
            }
            searchParameter = txtCari.getText();
            List<Soal> list = soalimpl.getSoalParameter(sqlParameter, searchParameter);
            soaltabmod.setData(list);
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }

    public void buttonPrint() {

        int row = tabelSoal.getRowCount();
        if (row == 0) {
            JOptionPane.showMessageDialog(this, "Tidak Ada Data Yang Di Cetak !");
        } else {
            try {
                //JasperPrint jasperPrint = kelasImplements.cetakKelas();
                //JasperViewer.viewReport(jasperPrint, false);
            } catch (Exception e) {
            }
        }
    }

    public void btnCariProdi() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
}
