/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsiannisameriana.quis;

import javax.swing.JOptionPane;
import skripsiannisameriana.soal.CariProdiView;

/**
 *
 * @author USER
 */
public class Prioritas extends javax.swing.JInternalFrame {
    
    //ProdiTabelModel prodiTabelModel = new ProdiTabelModel();
    //ProdiImplements prodiImplements = new ProdiImplements();
    /**
     * Creates new form Prioritas
     */
    public Prioritas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPilihProdi1 = new javax.swing.JTextField();
        txtPilihFak1 = new javax.swing.JTextField();
        btnPilih1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPilihFak2 = new javax.swing.JTextField();
        txtPilihProdi2 = new javax.swing.JTextField();
        btnPilih2 = new javax.swing.JButton();
        txtPilihProdi3 = new javax.swing.JTextField();
        btnPilih3 = new javax.swing.JButton();
        txtPilihFak3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPilihFak4 = new javax.swing.JTextField();
        txtPilihProdi4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPilih4 = new javax.swing.JButton();
        txtPilihFak5 = new javax.swing.JTextField();
        btnPilih5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPilihProdi5 = new javax.swing.JTextField();
        txtPilihFak6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPilihProdi6 = new javax.swing.JTextField();
        btnPilih6 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnIkutTes = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Silahkan Pilih Program Studi Prioritas Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pilihan Pertama          :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));
        jPanel1.add(txtPilihProdi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 260, -1));
        jPanel1.add(txtPilihFak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, -1));

        btnPilih1.setText("Pilihan 1");
        btnPilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel2.setText("Pilihan Kedua             :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));
        jPanel1.add(txtPilihFak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, -1));
        jPanel1.add(txtPilihProdi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 260, -1));

        btnPilih2.setText("Pilihan 2");
        btnPilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));
        jPanel1.add(txtPilihProdi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 260, -1));

        btnPilih3.setText("Pilihan 3");
        btnPilih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));
        jPanel1.add(txtPilihFak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, -1));

        jLabel3.setText("Pilihan Ketiga             :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));
        jPanel1.add(txtPilihFak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));
        jPanel1.add(txtPilihProdi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 260, -1));

        jLabel4.setText("Pilihan Keempat         :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        btnPilih4.setText("Pilihan 4");
        btnPilih4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));
        jPanel1.add(txtPilihFak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, -1));

        btnPilih5.setText("Pilihan 5");
        btnPilih5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabel5.setText("Pilihan Kelima             :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));
        jPanel1.add(txtPilihProdi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 260, -1));
        jPanel1.add(txtPilihFak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, -1));

        jLabel6.setText("Pilihan Keenam          :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, -1));
        jPanel1.add(txtPilihProdi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 260, -1));

        btnPilih6.setText("Pilihan 6");
        btnPilih6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 150, -1));

        btnIkutTes.setText("Ikut Tes");
        jPanel1.add(btnIkutTes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        buttonBatal();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnPilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih1ActionPerformed
        btnCariProdi1();
    }//GEN-LAST:event_btnPilih1ActionPerformed

    private void btnPilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih2ActionPerformed
        btnCariProdi2();
    }//GEN-LAST:event_btnPilih2ActionPerformed

    private void btnPilih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih3ActionPerformed
        btnCariProdi3();
    }//GEN-LAST:event_btnPilih3ActionPerformed

    private void btnPilih4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih4ActionPerformed
        btnCariProdi4();
    }//GEN-LAST:event_btnPilih4ActionPerformed

    private void btnPilih5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih5ActionPerformed
        btnCariProdi5();
    }//GEN-LAST:event_btnPilih5ActionPerformed

    private void btnPilih6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih6ActionPerformed
        btnCariProdi6();
    }//GEN-LAST:event_btnPilih6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnIkutTes;
    private javax.swing.JButton btnPilih1;
    private javax.swing.JButton btnPilih2;
    private javax.swing.JButton btnPilih3;
    private javax.swing.JButton btnPilih4;
    private javax.swing.JButton btnPilih5;
    private javax.swing.JButton btnPilih6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPilihFak1;
    private javax.swing.JTextField txtPilihFak2;
    private javax.swing.JTextField txtPilihFak3;
    private javax.swing.JTextField txtPilihFak4;
    private javax.swing.JTextField txtPilihFak5;
    private javax.swing.JTextField txtPilihFak6;
    private javax.swing.JTextField txtPilihProdi1;
    private javax.swing.JTextField txtPilihProdi2;
    private javax.swing.JTextField txtPilihProdi3;
    private javax.swing.JTextField txtPilihProdi4;
    private javax.swing.JTextField txtPilihProdi5;
    private javax.swing.JTextField txtPilihProdi6;
    // End of variables declaration//GEN-END:variables

    public void buttonBatal() {
        try {
            //Home2.setEnableDisableMenu(true);
            dispose();
            //Home2.isMenuItemKelasActive = false;
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi1() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi2() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi3() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi4() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi5() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
    
    public void btnCariProdi6() {
        try {
            CariProdiView cariProdiView = new CariProdiView(null, true);
            cariProdiView.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan !");
        }
    }
}
