/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsiannisameriana.quis;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import skripsiannisameriana.connect.Connect;
import skripsiannisameriana.home.Home1;

/**
 *
 * @author USER
 */
public class QuisView extends javax.swing.JInternalFrame {

    Connect k = new Connect();
    ResultSet rs, rs1, rs2, rs3, rs4;
    String[] jawaban;
    String[] jw;
    int i = 0, p = 0;
    PreparedStatement ps;
    public static int id;
    int[] ro;

    //save jawaban
    int id_soal1;
    int id_fak1;
    int id_pro1;
    int id_pend1;

    //save jawaban ke array
    int[] hasil;
    int[] id_fak;
    int[] id_pro;
    int[] id_pend;
    int[] id_soal;

    /**
     * Creates new form QuisView
     */
    public QuisView() {

        initComponents();
        tampil();
        try {
            String sql = "SELECT * FROM tb_soal ORDER BY id_soal";
            Statement s2 = Connect.getConnection().createStatement();
            rs3 = s2.executeQuery(sql);
            int jml = 0;
            while (rs3.next()) {
                jml++;
            }

            rs4 = k.select("SELECT * FROM tb_pilihan");
            int jlh = 1;
            while (rs4.next()) {
                jlh++;
            }
            for (int ko = 0; ko < jml; ko++) {
                for(int jo = 1; jo <= jlh; jo++){
                    ro[ko] = jo;
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(QuisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPilih = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jR4 = new javax.swing.JRadioButton();
        jR1 = new javax.swing.JRadioButton();
        jR2 = new javax.swing.JRadioButton();
        jR3 = new javax.swing.JRadioButton();
        btnResult = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUIS PEMILIHAN PROGRAM STUDI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bGPilih.add(jR4);
        jPanel1.add(jR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        bGPilih.add(jR1);
        jPanel1.add(jR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bGPilih.add(jR2);
        jPanel1.add(jR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        bGPilih.add(jR3);
        jPanel1.add(jR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnResult.setText("Result");
        btnResult.setEnabled(false);
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });
        jPanel1.add(btnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (jR1.isSelected()) {
            jawaban[p] = "a";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();

        } else if (jR2.isSelected()) {
            jawaban[p] = "b";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        } else if (jR3.isSelected()) {
            jawaban[p] = "c";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        } else {
            jawaban[p] = "d";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        if (jR1.isSelected()) {
            jawaban[p] = "a";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        } else if (jR2.isSelected()) {
            jawaban[p] = "b";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        } else if (jR3.isSelected()) {
            jawaban[p] = "c";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        } else {
            jawaban[p] = "d";
            id_soal[p] = id_soal1;
            id_fak[p] = id_fak1;
            id_pro[p] = id_pro1;
            p++;
            next_soal();
        }

        String sql1 = "SELECT * FROM tb_soal ORDER BY id_soal";
        try {

            Statement s1 = Connect.getConnection().createStatement();
            rs1 = s1.executeQuery(sql1);

            int r = 0;
            while (rs1.next()) {
                int nilai1 = rs1.getInt("nilai_a");
                int nilai2 = rs1.getInt("nilai_b");
                int nilai3 = rs1.getInt("nilai_c");
                int nilai4 = rs1.getInt("nilai_d");

                if (jawaban[r].equals("a")) {
                    hasil[r] = nilai1;
                    id_pend[r] = id;
                } else if (jawaban[r].equals("b")) {
                    hasil[r] = nilai2;
                    id_pend[r] = id;
                } else if (jawaban[r].equals("c")) {
                    hasil[r] = nilai3;
                    id_pend[r] = id;
                } else {
                    hasil[r] = nilai4;
                    id_pend[r] = id;
                }
                r++;
            }
            rs1.close();

            String sql = "SELECT * FROM tb_soal ORDER BY id_soal";
            Statement s2 = Connect.getConnection().createStatement();
            rs3 = s2.executeQuery(sql);
            int jml = 0;
            while (rs3.next()) {
                jml++;
            }

            rs4 = k.select("SELECT * FROM tb_pilihan");
            int jlh = 1;
            for (int ko = 0; ko < jml; ko++) {
                while (rs4.next()) {
                    jlh++;
                }
            }
            
            String sql4 = "INSERT INTO tb_hasil (hasil, id_soal , id_urut, id_pendaftar, id_fakultas, id_prodi)VALUES (?, ?, ?, ?, ?, ?)";
            ps = Connect.getConnection().prepareStatement(sql4);
            for (int k = 0; k < jml; k++) {
                ps.setInt(1, hasil[k]);
                ps.setInt(2, id_soal[k]);
                ps.setInt(3, ro[k]);
                ps.setInt(4, id_pend[k]);
                ps.setInt(5, id_fak[k]);
                ps.setInt(6, id_pro[k]);
                ps.executeUpdate();
            }

            AnalisisSPKTampil tampil3 = new AnalisisSPKTampil();
            Home1.jDesktopPane2.add(tampil3);
            tampil3.setVisible(true);
            this.dispose();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGPilih;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jR1;
    private javax.swing.JRadioButton jR2;
    private javax.swing.JRadioButton jR3;
    private javax.swing.JRadioButton jR4;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        String sql = "SELECT * FROM tb_soal ORDER BY id_soal";
        try {

            Statement s = Connect.getConnection().createStatement();
            rs = s.executeQuery(sql);

            rs.next();
            String soal = rs.getString("soal");
            id_soal1 = rs.getInt("id_soal");
            id_fak1 = rs.getInt("id_fakultas");
            id_pro1 = rs.getInt("id_prodi");
            String a = rs.getString("a");
            String b = rs.getString("b");
            String c = rs.getString("c");
            String d = rs.getString("d");

            jLabel1.setText(soal);
            jR1.setText(a);
            jR2.setText(b);
            jR3.setText(c);
            jR4.setText(d);

            i++;

            Statement s1 = Connect.getConnection().createStatement();
            rs2 = s1.executeQuery(sql);
            int jml_kriteria = 0;
            while (rs2.next()) {
                jml_kriteria++;
            }

            hasil = new int[jml_kriteria];
            id_fak = new int[jml_kriteria];
            id_pro = new int[jml_kriteria];
            id_pend = new int[jml_kriteria];
            id_soal = new int[jml_kriteria];
            jawaban = new String[jml_kriteria];
            jw = new String[jml_kriteria];

        } catch (Exception e) {
        }
    }

    //next soal
    private void next_soal() {
        try {
            if (rs.next()) {
                String soal = rs.getString("soal");
                id_soal1 = rs.getInt("id_soal");
                id_fak1 = rs.getInt("id_fakultas");
                id_pro1 = rs.getInt("id_prodi");
                String a = rs.getString("a");
                String b = rs.getString("b");
                String c = rs.getString("c");
                String d = rs.getString("d");

                jLabel1.setText(soal);
                jR1.setText(a);
                jR2.setText(b);
                jR3.setText(c);
                jR4.setText(d);
                chek_button();
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void chek_button() {
        try {
            if (rs.isLast()) {
                btnResult.setEnabled(true);
                btnNext.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
